version: "3"
services:

  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8081:80
    volumes:
      - ./wp_html:/var/www/html
    #volumes:
    #   - wp_html:/var/www/html

  editor:
    image: cmarin/csi-wp-plugin-editor
    links:
      - wordpress:wordpress
    ports:
      - 3000:80
    depends_on:
      - wordpress
    volumes:
      - ./wp_html/wp-content/plugins:/plugins
    #volumes:
    #  - wp_html:/var/www/html

  wordpress_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Demo_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: Demo_pass

#volumes:
#  wp_html:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./wp_html
