
  wordpress:
    image: cmarin/intranet:latest
#    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 80:80
    volumes:
      - ./wp_html:/var/www/html

  wordpress_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Demo_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    image: corbinu/docker-phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: Demo_pass
